### ISSUE TITLE
How to solve?

### ISSUE THREAD

**Issue by hotmoon6** [tomyangsh/dmmbot#2]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3662): Max retries exceeded with url: /api/top (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f57fbab8850>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by tomyangsh** [comment]
Like I told you, could you please rebase to `cafea68` then modify the project? Please learn some python instead of wasting our time.
